const data = {
  "A": {
    "Actor / Actress": ["Al Pacino/ Amy Adams"],
    "Alcoholic Drink": ["Amaretto"],
    "Animal": ["Alligator"],
    "Artist (Female singer)": ["Anne-Marie"],
    "Artist (Male singer)": ["Akon"],
    "Band": ["ABBA"],
    "Bird": ["Albatross"],
    "Body part (human)": ["Arm"],
    "Book title": ["Atonement"],
    "Boys name": ["Alex"],
    "Car make / Model": ["Audi / Astra"],
    "Colour": ["Aqua"],
    "Country": ["Argentina"],
    "Dog breed": ["Akita"],
    "Drink": ["Apple juice"],
    "Eat (Food)": ["Apple"],
    "Electrical appliance": ["Alarm clock"],
    "Fictional character": ["Aladdin"],
    "Film": ["Avengers"],
    "Fish": ["Anchovy"],
    "Football team (UK)": ["Arsenal"],
    "Foreign city": ["Athens"],
    "Foreign language": ["Arabic"],
    "Fruit / Vegetable": ["Apple / Asparagus"],
    "Girls name": ["Amy"],
    "Hobby": ["Astrology"],
    "Job title": ["Artist"],
    "Musical instrument": ["Accordian"],
    "Plant or flower": ["Amaryllis"],
    "School Subject": ["Art"],
    "Shop": ["Apple"],
    "Song title": ["Alright"],
    "Sport": ["American Football"],
    "Sports star": ["Adam Peaty"],
    "TV show": ["Archer"],
    "UK City / Town": ["Aberdeen / Alsager"],
    "Wear (Clothing item)": ["Apron"],
    "Word ending in ED": ["Aimed"],
    "Word ending in ING": ["Aching"],
    "3/4/5 letter word": ["Arm / Army/ Angry"],
  },

  "B": {
    "Actor / Actress": ["Brad Pitt / Blake Lively"],
    "Alcoholic Drink": ["Brandy"],
    "Animal": ["Bull"],
    "Artist (Female singer)": ["Billie Eilish"],
    "Artist (Male singer)": ["Bruno Mars"],
    "Band": ["Blue"],
    "Bird": ["Blackbird"],
    "Body part (human)": ["Brain"],
    "Book title": ["The Book Thief"],
    "Boys name": ["Ben"],
    "Car make / Model": ["Bugatti / Bora"],
    "Colour": ["Black"],
    "Country": ["Belgium"],
    "Dog breed": ["Bulldog"],
    "Drink": ["Beer"],
    "Eat (Food)": ["Bread"],
    "Electrical appliance": ["Blender"],
    "Fictional character": ["Batman"],
    "Film": ["Bad Boys"],
    "Fish": ["Bream"],
    "Football team (UK)": ["Blackburn Rovers"],
    "Foreign city": ["Berlin"],
    "Foreign language": ["Bulgarian"],
    "Fruit / Vegetable": ["Blackberry / Broad bean"],
    "Girls name": ["Becky"],
    "Hobby": ["Board games"],
    "Job title": ["Builder"],
    "Musical instrument": ["Banjo"],
    "Plant or flower": ["Begonia"],
    "School Subject": ["Business Studies"],
    "Shop": ["Boots"],
    "Song title": ["Bad Blood"],
    "Sport": ["Baseball"],
    "Sports star": ["Boris Becker"],
    "TV show": ["Brassic"],
    "UK City / Town": ["Bath / Barnsley"],
    "Wear (Clothing item)": ["Boots"],
    "Word ending in ED": ["Bored"],
    "Word ending in ING": ["Banging"],
    "3/4/5 letter word": ["Bar / Barn / Bread"],
  },

  "C": {
    "Actor / Actress": ["Chris Pratt / Claire Danes"],
    "Alcoholic Drink": ["Cider"],
    "Animal": ["Cat"],
    "Artist (Female singer)": ["Cher"],
    "Artist (Male singer)": ["Calvin Harris"],
    "Band": ["Cast"],
    "Bird": ["Crow"],
    "Body part (human)": ["Chin"],
    "Book title": ["Cold Mountain"],
    "Boys name": ["Chris"],
    "Car make / Model": ["Citroën / Clio"],
    "Colour": ["Cream"],
    "Country": ["Canada"],
    "Dog breed": ["Chihuahua"],
    "Drink": ["Coffee"],
    "Eat (Food)": ["Cereal"],
    "Electrical appliance": ["Computer"],
    "Fictional character": ["Cinderella"],
    "Film": ["Crash"],
    "Fish": ["Cod"],
    "Football team (UK)": ["Crewe Alex"],
    "Foreign city": ["Copenhagen"],
    "Foreign language": ["Chinese"],
    "Fruit / Vegetable": ["Clementine / Carrot"],
    "Girls name": ["Chloe"],
    "Hobby": ["Computing"],
    "Job title": ["Chemist"],
    "Musical instrument": ["Cello"],
    "Plant or flower": ["Carnation"],
    "School Subject": ["Chemistry"],
    "Shop": ["Co-op"],
    "Song title": ["Cool"],
    "Sport": ["Cricket"],
    "Sports star": ["Chris Eubank"],
    "TV show": ["Castle"],
    "UK City / Town": ["Cardiff / Crawley"],
    "Wear (Clothing item)": ["Coat"],
    "Word ending in ED": ["Cured"],
    "Word ending in ING": ["Crashing"],
    "3/4/5 letter word": ["Car / Card / Crash"],
  },

  "D": {
    "Actor / Actress": ["Denzel Washington / Demi Moore"],
    "Alcoholic Drink": ["Daiquiri"],
    "Animal": ["Dog"],
    "Artist (Female singer)": ["Dido"],
    "Artist (Male singer)": ["Drake"],
    "Band": ["The Doors"],
    "Bird": ["Dipper"],
    "Body part (human)": ["Diaphragm"],
    "Book title": ["Dracula"],
    "Boys name": ["Dan"],
    "Car make / Model": ["Dacia / Duster"],
    "Colour": ["Denim"],
    "Country": ["Denmark"],
    "Dog breed": ["Dachshund"],
    "Drink": ["Dr Pepper"],
    "Eat (Food)": ["Donut"],
    "Electrical appliance": ["DVD player"],
    "Fictional character": ["Dumbo"],
    "Film": ["Die Hard"],
    "Fish": ["Dartfish"],
    "Football team (UK)": ["Derby County"],
    "Foreign city": ["Doha"],
    "Foreign language": ["Danish"],
    "Fruit / Vegetable": ["Dragonfruit / Daikon"],
    "Girls name": ["Diana"],
    "Hobby": ["Dancing"],
    "Job title": ["DJ"],
    "Musical instrument": ["Drums"],
    "Plant or flower": ["Daisy"],
    "School Subject": ["Drama"],
    "Shop": ["DFS"],
    "Song title": ["Dare"],
    "Sport": ["Darts"],
    "Sports star": ["David Beckham"],
    "TV show": ["Dexter"],
    "UK City / Town": ["Derby / Dagenham"],
    "Wear (Clothing item)": ["Dress"],
    "Word ending in ED": ["Dared"],
    "Word ending in ING": ["Dancing"],
    "3/4/5 letter word": ["Dot / Dote / Doted"],
  },

  "E": {
    "Actor / Actress": ["Eddie Murphy / Emma Stone"],
    "Alcoholic Drink": ["Erdinger"],
    "Animal": ["Elk"],
    "Artist (Female singer)": ["Ella Henderson"],
    "Artist (Male singer)": ["Ed Sheeran"],
    "Band": ["The Eagles"],
    "Bird": ["Eagle"],
    "Body part (human)": ["Ear"],
    "Book title": ["East of Eden"],
    "Boys name": ["Eric"],
    "Car make / Model": ["Eagle / Escort"],
    "Colour": ["Emerald green"],
    "Country": ["Egypt"],
    "Dog breed": ["Eurasier"],
    "Drink": ["Espresso"],
    "Eat (Food)": ["Eggs"],
    "Electrical appliance": ["Electric car"],
    "Fictional character": ["Elmo"],
    "Film": ["Eternals"],
    "Fish": ["Eel"],
    "Football team (UK)": ["Everton"],
    "Foreign city": ["Eindhoven / Edinburgh"],
    "Foreign language": ["Egyptian"],
    "Fruit / Vegetable": ["Elderberry / Edamame bean"],
    "Girls name": ["Ellie"],
    "Hobby": ["Exercise"],
    "Job title": ["Editor"],
    "Musical instrument": ["Ektara"],
    "Plant or flower": ["Echinacea"],
    "School Subject": ["English"],
    "Shop": ["EE"],
    "Song title": ["Emotion"],
    "Sport": ["Equestrian"],
    "Sports star": ["Eric Cantona"],
    "TV show": ["Emmerdale"],
    "UK City / Town": ["Edinburgh / Eastleigh"],
    "Wear (Clothing item)": ["Earrings"],
    "Word ending in ED": ["Earned"],
    "Word ending in ING": ["Ending"],
    "3/4/5 letter word": ["Eve / Ever / Earth"],
  },

  "F": {
    "Actor / Actress": ["Freddy Prince Jr / Felicity Jones"],
    "Alcoholic Drink": ["Fosters"],
    "Animal": ["Frog"],
    "Artist (Female singer)": ["Fergie"],
    "Artist (Male singer)": ["Freddie Mercury"],
    "Band": ["Foreigner"],
    "Bird": ["Firecrest"],
    "Body part (human)": ["Foot"],
    "Book title": ["Frankenstein"],
    "Boys name": ["Fred"],
    "Car make / Model": ["Ford / Fabia"],
    "Colour": ["Fuchsia"],
    "Country": ["France"],
    "Dog breed": ["Foxhound"],
    "Drink": ["Fanta"],
    "Eat (Food)": ["Falafel"],
    "Electrical appliance": ["Fridge"],
    "Fictional character": ["Fred Flintstone"],
    "Film": ["Fargo"],
    "Fish": ["Flounder"],
    "Football team (UK)": ["Fulham"],
    "Foreign city": ["Florence / Funafuti"],
    "Foreign language": ["French"],
    "Fruit / Vegetable": ["Fig / Fennel"],
    "Girls name": ["Fay"],
    "Hobby": ["Fishing"],
    "Job title": ["Farmer"],
    "Musical instrument": ["Fiddle"],
    "Plant or flower": ["Freesia"],
    "School Subject": ["French"],
    "Shop": ["Fossil"],
    "Song title": ["Firework"],
    "Sport": ["Football"],
    "Sports star": ["Freddie Flintoff"],
    "TV show": ["Friends"],
    "UK City / Town": ["/Falkirk"],
    "Wear (Clothing item)": ["Face mask"],
    "Word ending in ED": ["Feared"],
    "Word ending in ING": ["Finding"],
    "3/4/5 letter word": ["Far / Farm / Fresh"],
  },

  "G": {
    "Actor / Actress": ["Gary Oldman / Gal Gadot"],
    "Alcoholic Drink": ["Gin"],
    "Animal": ["Giraffe"],
    "Artist (Female singer)": ["Gwen Stefani"],
    "Artist (Male singer)": ["George Ezra"],
    "Band": ["Genesis"],
    "Bird": ["Goose"],
    "Body part (human)": ["Gums"],
    "Book title": ["Gullivers travels"],
    "Boys name": ["Geoff"],
    "Car make / Model": ["GMC / Golf"],
    "Colour": ["Green"],
    "Country": ["Germany"],
    "Dog breed": ["German Shepherd"],
    "Drink": ["Gin"],
    "Eat (Food)": ["Grapes"],
    "Electrical appliance": ["Grill"],
    "Fictional character": ["Goofy"],
    "Film": ["Grease"],
    "Fish": ["Goldfish"],
    "Football team (UK)": ["Grimsby town"],
    "Foreign city": ["Gdansk / Guatemala City"],
    "Foreign language": ["German"],
    "Fruit / Vegetable": ["Grape / Gherkin"],
    "Girls name": ["Grace"],
    "Hobby": ["Gaming"],
    "Job title": ["Gardener"],
    "Musical instrument": ["Guitar"],
    "Plant or flower": ["Geranium"],
    "School Subject": ["German"],
    "Shop": ["Gap"],
    "Song title": ["Golden"],
    "Sport": ["Gymnastics"],
    "Sports star": ["George Best"],
    "TV show": ["Grange Hill"],
    "UK City / Town": ["Glasgow / Gosport"],
    "Wear (Clothing item)": ["Gloves"],
    "Word ending in ED": ["Graded"],
    "Word ending in ING": ["Grinding"],
    "3/4/5 letter word": ["Got / Goat / Grand"],
  },

  "H": {
    "Actor / Actress": ["Henry Cavill/ Halle Berry"],
    "Alcoholic Drink": ["Heineken"],
    "Animal": ["Horse"],
    "Artist (Female singer)": ["H.E.R"],
    "Artist (Male singer)": ["Harry Styles"],
    "Band": ["Honeyz"],
    "Bird": ["Hawk"],
    "Body part (human)": ["Head"],
    "Book title": ["The Hobbit"],
    "Boys name": ["Harry"],
    "Car make / Model": ["Hyundai / Hatch"],
    "Colour": ["Hot pink"],
    "Country": ["Holland"],
    "Dog breed": ["Harrier"],
    "Drink": ["Horlicks"],
    "Eat (Food)": ["Hummus"],
    "Electrical appliance": ["Hair dryer"],
    "Fictional character": ["Harry Potter"],
    "Film": ["Heat"],
    "Fish": ["Haddock"],
    "Football team (UK)": ["Hull city"],
    "Foreign city": ["Helsinki"],
    "Foreign language": ["Hungarian"],
    "Fruit / Vegetable": ["Honeydew Melon / Horseradish"],
    "Girls name": ["Holly"],
    "Hobby": ["Hiking"],
    "Job title": ["Hairdresser"],
    "Musical instrument": ["Harp"],
    "Plant or flower": ["Heather"],
    "School Subject": ["History"],
    "Shop": ["HMV"],
    "Song title": ["Hello"],
    "Sport": ["Hockey"],
    "Sports star": ["Harry Maguire"],
    "TV show": ["House"],
    "UK City / Town": ["Hereford / Halifax"],
    "Wear (Clothing item)": ["Hat"],
    "Word ending in ED": ["Hired"],
    "Word ending in ING": ["Hosting"],
    "3/4/5 letter word": ["Hot / Host / Hoard"],
  },

  "I": {
    "Actor / Actress": ["Idris Elba / Isla Fisher"],
    "Alcoholic Drink": ["IPA"],
    "Animal": ["Iguana"],
    "Artist (Female singer)": ["Iggy Azalea"],
    "Artist (Male singer)": ["Iggy Pop"],
    "Band": ["INXS"],
    "Bird": ["Ibisbill"],
    "Body part (human)": ["Intestine"],
    "Book title": ["The invisible man"],
    "Boys name": ["Ian"],
    "Car make / Model": ["Infiniti / Ibiza"],
    "Colour": ["Indigo"],
    "Country": ["Iceland"],
    "Dog breed": ["Irish wolfhound"],
    "Drink": ["Iced tea"],
    "Eat (Food)": ["Ice cream"],
    "Electrical appliance": ["Iron"],
    "Fictional character": ["Iron Man"],
    "Film": ["It"],
    "Fish": ["Ide"],
    "Football team (UK)": ["Ipswich town"],
    "Foreign city": ["Irakleion / Islamabad"],
    "Foreign language": ["Icelandic"],
    "Fruit / Vegetable": ["Ilama / Iceberg Lettuce"],
    "Girls name": ["Isabelle"],
    "Hobby": ["Ice skating"],
    "Job title": ["Illustrator"],
    "Musical instrument": ["Igil"],
    "Plant or flower": ["Iris"],
    "School Subject": ["I.T"],
    "Shop": ["Iceland"],
    "Song title": ["In my head"],
    "Sport": ["Ice skating"],
    "Sports star": ["Ian Wright"],
    "TV show": ["Intelligence"],
    "UK City / Town": ["Inverness / Ipswich"],
    "Wear (Clothing item)": ["Insoles"],
    "Word ending in ED": ["Inked"],
    "Word ending in ING": ["Imploding"],
    "3/4/5 letter word": ["Ink / Idle / Indie"],
  },

  "J": {
    "Actor / Actress": ["Jack Black / Jodie Comer"],
    "Alcoholic Drink": ["Jack Daniels"],
    "Animal": ["Jackal"],
    "Artist (Female singer)": ["Jennifer Lopez"],
    "Artist (Male singer)": ["James Bay"],
    "Band": ["Journey"],
    "Bird": ["Jay"],
    "Body part (human)": ["Jaw"],
    "Book title": ["Jane Eyre"],
    "Boys name": ["Jack"],
    "Car make / Model": ["Jeep / Juke"],
    "Colour": ["Jade"],
    "Country": ["Jamaica"],
    "Dog breed": ["Jack Russell"],
    "Drink": ["J20"],
    "Eat (Food)": ["Jelly"],
    "Electrical appliance": ["Juicer"],
    "Fictional character": ["Jack Skellington"],
    "Film": ["Joker"],
    "Fish": ["Jawfish"],
    "Foreign city": ["Jerusalem"],
    "Foreign language": ["Japanese"],
    "Fruit / Vegetable": ["Juniper Berries / Jalapeño"],
    "Girls name": ["Jodie"],
    "Hobby": ["Jigsaw puzzles"],
    "Job title": ["Jeweller"],
    "Musical instrument": ["Jug"],
    "Plant or flower": ["Jasmine"],
    "School Subject": ["Japanese"],
    "Shop": ["Jigsaw"],
    "Song title": ["Jump"],
    "Sport": ["Judo"],
    "Sports star": ["Jamie Vardy"],
    "TV show": ["Joey"],
    "UK City / Town": ["/John O' Groats"],
    "Wear (Clothing item)": ["Jacket"],
    "Word ending in ED": ["Jumped"],
    "Word ending in ING": ["Jumping"],
    "3/4/5 letter word": ["Jar / Jump / Joust"],
  },

  "K": {
    "Actor / Actress": ["Kurt Russell / Kristen Stewart"],
    "Alcoholic Drink": ["Kopperberg"],
    "Animal": ["Komodo dragon"],
    "Artist (Female singer)": ["Katy Perry"],
    "Artist (Male singer)": ["Kanye West"],
    "Band": ["Kiss"],
    "Bird": ["Kestrel"],
    "Body part (human)": ["Knuckle"],
    "Book title": ["King Lear"],
    "Boys name": ["Ken"],
    "Car make / Model": ["Kia / KA"],
    "Colour": ["Khaki"],
    "Country": ["Kenya"],
    "Dog breed": ["Keeshond"],
    "Drink": ["Kia Ora"],
    "Eat (Food)": ["Kiwi"],
    "Electrical appliance": ["Kettle"],
    "Fictional character": ["Kermit the frog"],
    "Film": ["King Kong"],
    "Fish": ["Koi"],
    "Football team (UK)": ["Kilmarnock"],
    "Foreign city": ["Krakow / Kabul"],
    "Foreign language": ["Korean"],
    "Fruit / Vegetable": ["Kiwi / Kale"],
    "Girls name": ["Kerry"],
    "Hobby": ["Knitting"],
    "Job title": ["Karate instructor"],
    "Musical instrument": ["Kazoo"],
    "Plant or flower": ["Kangaroo paw"],
    "School Subject": ["Korean"],
    "Shop": ["Krispy Kreme"],
    "Song title": ["King"],
    "Sport": ["Karate"],
    "Sports star": ["Kelly Holmes"],
    "TV show": ["Killing Eve"],
    "UK City / Town": ["Kingston upon Hull / Knutsford"],
    "Wear (Clothing item)": ["Kimono"],
    "Word ending in ED": ["Kicked"],
    "Word ending in ING": ["Kissing"],
    "3/4/5 letter word": ["Kit / Kite / Kneel"],
  },

  "L": {
    "Actor / Actress": ["Luke Evans / Liv Tyler"],
    "Alcoholic Drink": ["Lambrini"],
    "Animal": ["Lynx"],
    "Artist (Female singer)": ["Lulu"],
    "Artist (Male singer)": ["Lionel Richie"],
    "Band": ["The Lumineers"],
    "Bird": ["Lapwing"],
    "Body part (human)": ["Leg"],
    "Book title": ["The Lorax"],
    "Boys name": ["Lee"],
    "Car make / Model": ["Lexus / Leon"],
    "Colour": ["Lilac"],
    "Country": ["Laos"],
    "Dog breed": ["Lurcher"],
    "Drink": ["Lilt"],
    "Eat (Food)": ["Lentils"],
    "Electrical appliance": ["Lamp"],
    "Fictional character": ["Lara Croft"],
    "Film": ["Lion"],
    "Fish": ["Ladyfish"],
    "Football team (UK)": ["Liverpool"],
    "Foreign city": ["Lisbon"],
    "Foreign language": ["Latin"],
    "Fruit / Vegetable": ["Lime / Leeks"],
    "Girls name": ["Lisa"],
    "Hobby": ["Lego building"],
    "Job title": ["Lifeguard"],
    "Musical instrument": ["Lute"],
    "Plant or flower": ["Lily"],
    "School Subject": ["Law"],
    "Shop": ["Lego"],
    "Song title": ["Lover"],
    "Sport": ["Lacrosse"],
    "Sports star": ["Lionel Messi"],
    "TV show": ["Luther"],
    "UK City / Town": ["Leeds / Luton"],
    "Wear (Clothing item)": ["Leggings"],
    "Word ending in ED": ["Liked"],
    "Word ending in ING": ["Lasting"],
    "3/4/5 letter word": ["Lap / Link / Large"],
  },

  "M": {
    "Actor / Actress": ["Matt Damon / Megan Fox"],
    "Alcoholic Drink": ["Mojito"],
    "Animal": ["Mouse"],
    "Artist (Female singer)": ["Mabel"],
    "Artist (Male singer)": ["Meat Loaf"],
    "Band": ["Metallica"],
    "Bird": ["Magpie"],
    "Body part (human)": ["Mouth"],
    "Book title": ["Matilda"],
    "Boys name": ["Matt"],
    "Car make / Model": ["Mini / Micra"],
    "Colour": ["Maroon"],
    "Country": ["Malaysia"],
    "Dog breed": ["Maltese"],
    "Drink": ["Milk"],
    "Eat (Food)": ["Mango"],
    "Electrical appliance": ["Mixer"],
    "Fictional character": ["Mario"],
    "Film": ["Marley & me"],
    "Fish": ["Mackerel"],
    "Football team (UK)": ["Manchester City"],
    "Foreign city": ["Madrid"],
    "Foreign language": ["Mandarin"],
    "Fruit / Vegetable": ["Mango / Mushroom"],
    "Girls name": ["Mandy"],
    "Hobby": ["Model building"],
    "Job title": ["Mechanic"],
    "Musical instrument": ["Maracas"],
    "Plant or flower": ["Magnolia"],
    "School Subject": ["Maths"],
    "Shop": ["Mango"],
    "Song title": ["Malibu"],
    "Sport": ["Martial Arts"],
    "Sports star": ["Mo Farah"],
    "TV show": ["Manifest"],
    "UK City / Town": ["Manchester / Macclesfield"],
    "Wear (Clothing item)": ["Mittens"],
    "Word ending in ED": ["Mined"],
    "Word ending in ING": ["Mining"],
    "3/4/5 letter word": ["Man / Main / Manly"],
  },

  "N": {
    "Actor / Actress": ["Nick Frost / Nicole Kidman"],
    "Alcoholic Drink": ["Negroni"],
    "Animal": ["Newt"],
    "Artist (Female singer)": ["Nancy Sinatra"],
    "Artist (Male singer)": ["Niall Horan"],
    "Band": ["Nirvana"],
    "Bird": ["Nightingale"],
    "Body part (human)": ["Neck"],
    "Book title": ["Nicholas Nickleby"],
    "Boys name": ["Neil"],
    "Car make / Model": ["Nissan / Navara"],
    "Colour": ["Navy blue"],
    "Country": ["New Zealand"],
    "Dog breed": ["Newfoundland"],
    "Drink": ["Naked smoothie"],
    "Eat (Food)": ["Noodles"],
    "Electrical appliance": ["Night light"],
    "Fictional character": ["Nancy Drew"],
    "Film": ["Notting Hill"],
    "Fish": ["Needlefish"],
    "Football team (UK)": ["Nottingham forest"],
    "Foreign city": ["Naples / Nassau"],
    "Foreign language": ["Norwegian"],
    "Fruit / Vegetable": ["Nectarine / Neeps"],
    "Girls name": ["Nina"],
    "Hobby": ["Naturism"],
    "Job title": ["Nurse"],
    "Musical instrument": ["Ney"],
    "Plant or flower": ["Nigella"],
    "School Subject": ["Nano physics"],
    "Shop": ["Next"],
    "Song title": ["Numb"],
    "Sport": ["Netball"],
    "Sports star": ["Nicola Adams"],
    "TV show": ["Neighbours"],
    "UK City / Town": ["Nowich / Northampton"],
    "Wear (Clothing item)": ["Necklace"],
    "Word ending in ED": ["Nailed"],
    "Word ending in ING": ["Napping"],
    "3/4/5 letter word": ["Nap / Near / Ninja"],
  },

  "O": {
    "Actor / Actress": ["Owen Wilson / Olivia Coleman"],
    "Alcoholic Drink": ["Ouzo"],
    "Animal": ["Ox"],
    "Artist (Female singer)": ["Olivia Rodrigo"],
    "Artist (Male singer)": ["Olly Murs"],
    "Band": ["Oasis"],
    "Bird": ["Osprey"],
    "Body part (human)": ["Ovaries"],
    "Book title": ["Oliver Twist"],
    "Boys name": ["Oscar"],
    "Car make / Model": ["Opel / Octavia"],
    "Colour": ["Orange"],
    "Country": ["Oman"],
    "Dog breed": ["Otterhound"],
    "Drink": ["Orange juice"],
    "Eat (Food)": ["Olives"],
    "Electrical appliance": ["Oven"],
    "Fictional character": ["Oliver Twist"],
    "Film": ["Oblivion"],
    "Fish": ["Opaleye"],
    "Football team (UK)": ["Oxford united"],
    "Foreign city": ["Oslo"],
    "Foreign language": ["Oromo"],
    "Fruit / Vegetable": ["Orange / Onion"],
    "Girls name": ["Olivia"],
    "Hobby": ["Origami"],
    "Job title": ["Orthodontist"],
    "Musical instrument": ["Organ"],
    "Plant or flower": ["Orchid"],
    "School Subject": ["Ornithology"],
    "Shop": ["O2"],
    "Song title": ["Old town road"],
    "Sport": ["Orienteering"],
    "Sports star": ["Oscar de la Hoya"],
    "TV show": ["Oz"],
    "UK City / Town": ["Oxford / Ormskirk"],
    "Wear (Clothing item)": ["Overalls"],
    "Word ending in ED": ["Owned"],
    "Word ending in ING": ["Owning"],
    "3/4/5 letter word": ["Own / Over / Owner"],
  },

  "P": {
    "Actor / Actress": ["Paul Hogan / Penelope Cruz"],
    "Alcoholic Drink": ["Port"],
    "Animal": ["Panda"],
    "Artist (Female singer)": ["Pink"],
    "Artist (Male singer)": ["Prince"],
    "Band": ["Pulp"],
    "Bird": ["Puffin"],
    "Body part (human)": ["Pelvis"],
    "Book title": ["Pride and prejudice"],
    "Boys name": ["Paul"],
    "Car make / Model": ["Porsche / Polo"],
    "Colour": ["Purple"],
    "Country": ["Peru"],
    "Dog breed": ["Pug"],
    "Drink": ["Pepsi"],
    "Eat (Food)": ["Pizza"],
    "Electrical appliance": ["Printer"],
    "Fictional character": ["Popeye"],
    "Film": ["Psycho"],
    "Fish": ["Plaice"],
    "Football team (UK)": ["Port vale"],
    "Foreign city": ["Pisa / Paris"],
    "Foreign language": ["Portuguese"],
    "Fruit / Vegetable": ["Plum / Parsnips"],
    "Girls name": ["Paige"],
    "Hobby": ["Photography"],
    "Job title": ["Plumber"],
    "Musical instrument": ["Piano"],
    "Plant or flower": ["Poppy"],
    "School Subject": ["P.E"],
    "Shop": ["Pandora"],
    "Song title": ["Perfect"],
    "Sport": ["Polo"],
    "Sports star": ["Paula Radcliffe"],
    "TV show": ["Pingu"],
    "UK City / Town": ["Perth / Paignton"],
    "Wear (Clothing item)": ["Pants"],
    "Word ending in ED": ["Posted"],
    "Word ending in ING": ["Posting"],
    "3/4/5 letter word": ["Pot / Post / Press"],
  },

  "Q": {
    "Actor / Actress": ["Quentin Tarantino / Queen Latifa"],
    "Animal": ["Quail"],
    "Artist (Female singer)": ["Queen Latifah"],
    "Artist (Male singer)": ["Quincy Jones"],
    "Band": ["Queen"],
    "Bird": ["Quail"],
    "Body part (human)": ["Quads"],
    "Book title": ["The Queens Gambit"],
    "Boys name": ["Quentin"],
    "Car make / Model": ["Qashqai"],
    "Colour": ["Quartz grey"],
    "Country": ["Qatar"],
    "Drink": ["Quaalude"],
    "Eat (Food)": ["Quiche"],
    "Fictional character": ["Quasimodo"],
    "Film": ["Quills"],
    "Fish": ["Quillfish"],
    "Football team (UK)": ["Queens park rangers"],
    "Foreign city": ["Quebec / Quito"],
    "Foreign language": ["Quechua"],
    "Fruit / Vegetable": ["Quince /"],
    "Girls name": ["Quinn"],
    "Hobby": ["Quilting"],
    "Job title": ["Quality controller"],
    "Musical instrument": ["Quatro"],
    "Plant or flower": ["Quince"],
    "Shop": ["Quiz"],
    "Song title": ["Queen of my heart"],
    "Sport": ["Quadrathlon"],
    "Sports star": ["Quincy Owusu-Abeyie"],
    "TV show": ["Quantum leap"],
    "UK City / Town": ["/Queensferry"],
    "Wear (Clothing item)": ["Quilted jacket"],
    "Word ending in ED": ["Quitted"],
    "Word ending in ING": ["Quitting"],
    "3/4/5 letter word": ["Qua / Quit / Quite"],
  },

  "R": {
    "Actor / Actress": ["Robert Pattinson/ Rebel Wilson"],
    "Alcoholic Drink": ["Rum"],
    "Animal": ["Rabbit"],
    "Artist (Female singer)": ["Rihanna"],
    "Artist (Male singer)": ["Ray Charles"],
    "Band": ["Radiohead"],
    "Bird": ["Robin"],
    "Body part (human)": ["Ribs"],
    "Book title": ["Romeo and Juliet"],
    "Boys name": ["Rob"],
    "Car make / Model": ["Range Rover/ Reliant"],
    "Colour": ["Red"],
    "Country": ["Russia"],
    "Dog breed": ["Rottweiler"],
    "Drink": ["Rum"],
    "Eat (Food)": ["Ramen"],
    "Electrical appliance": ["Radio"],
    "Fictional character": ["Rapunzel"],
    "Film": ["Rambo"],
    "Fish": ["Rainbowfish"],
    "Football team (UK)": ["Rotherham united"],
    "Foreign city": ["Rome"],
    "Foreign language": ["Romanian"],
    "Fruit / Vegetable": ["Raisin / Radish"],
    "Girls name": ["Rachel"],
    "Hobby": ["Reading"],
    "Job title": ["Reporter"],
    "Musical instrument": ["Recorder"],
    "Plant or flower": ["Rose"],
    "School Subject": ["R.E"],
    "Shop": ["River Island"],
    "Song title": ["Roar"],
    "Sport": ["Rowing"],
    "Sports star": ["Rebecca Adlington"],
    "TV show": ["Revenge"],
    "UK City / Town": ["Ripon / Rochester"],
    "Wear (Clothing item)": ["Ring"],
    "Word ending in ED": ["Ripped"],
    "Word ending in ING": ["Ripping"],
    "3/4/5 letter word": ["Rip / Ripe / Ripen"],
  },

  "S": {
    "Actor / Actress": ["Steve Martin / Sandra Bullock"],
    "Alcoholic Drink": ["Sambuca"],
    "Animal": ["Shrew"],
    "Artist (Female singer)": ["Shakira"],
    "Artist (Male singer)": ["Sting"],
    "Band": ["Supergrass"],
    "Bird": ["Swift"],
    "Body part (human)": ["Stomach"],
    "Book title": ["Stuart little"],
    "Boys name": ["Sam"],
    "Car make / Model": ["Seat / Sierra"],
    "Colour": ["Silver"],
    "Country": ["Sweden"],
    "Dog breed": ["Saluki"],
    "Drink": ["Sangria"],
    "Eat (Food)": ["Soup"],
    "Electrical appliance": ["Scanner"],
    "Fictional character": ["Shrek"],
    "Film": ["Scream"],
    "Fish": ["Salmon"],
    "Football team (UK)": ["Southampton"],
    "Foreign city": ["Seville / Stockholm"],
    "Foreign language": ["Spanish"],
    "Fruit / Vegetable": ["Strawberry / Swede"],
    "Girls name": ["Sarah"],
    "Hobby": ["Sewing"],
    "Job title": ["Supervisor"],
    "Musical instrument": ["Sitar"],
    "Plant or flower": ["Snowdrop"],
    "School Subject": ["Spanish"],
    "Shop": ["Superdrug"],
    "Song title": ["Sorry"],
    "Sport": ["Sailing"],
    "Sports star": ["Serena Williams"],
    "TV show": ["Scandal"],
    "UK City / Town": ["Salisbury / Sale"],
    "Wear (Clothing item)": ["Shorts"],
    "Word ending in ED": ["Seed"],
    "Word ending in ING": ["Singing"],
    "3/4/5 letter word": ["See / Seat / Sleep"],
  },

  "T": {
    "Actor / Actress": ["Tom Hanks / Tyra Banks"],
    "Alcoholic Drink": ["Tequila"],
    "Animal": ["Turtle"],
    "Artist (Female singer)": ["Toni Braxton"],
    "Artist (Male singer)": ["Tom Jones"],
    "Band": ["Texas"],
    "Bird": ["Toucan"],
    "Body part (human)": ["Thigh"],
    "Book title": ["Thumbelina"],
    "Boys name": ["Tom"],
    "Car make / Model": ["Toyota / T-Cross"],
    "Colour": ["Turquoise"],
    "Country": ["Thailand"],
    "Dog breed": ["Terrier"],
    "Drink": ["Tea"],
    "Eat (Food)": ["Tofu"],
    "Electrical appliance": ["TV"],
    "Fictional character": ["Tigger"],
    "Film": ["Thor"],
    "Fish": ["Trout"],
    "Football team (UK)": ["Tottenham hotspur"],
    "Foreign city": ["Toronto"],
    "Foreign language": ["Thai"],
    "Fruit / Vegetable": ["Tangerine / Turnip"],
    "Girls name": ["Tina"],
    "Hobby": ["Travelling"],
    "Job title": ["Teacher"],
    "Musical instrument": ["Trumpet"],
    "Plant or flower": ["Tulip"],
    "School Subject": ["Textiles"],
    "Shop": ["Tesco"],
    "Song title": ["Try"],
    "Sport": ["Tennis"],
    "Sports star": ["Tim Henman"],
    "TV show": ["Teachers"],
    "UK City / Town": ["Truro / Tamworth"],
    "Wear (Clothing item)": ["Tie"],
    "Word ending in ED": ["Tied"],
    "Word ending in ING": ["Trying"],
    "3/4/5 letter word": ["Tea / Taxi / Train"],
  },

  "U": {
    "Actor / Actress": ["Uma Thurman"],
    "Animal": ["Urchin"],
    "Artist (Male singer)": ["Usher"],
    "Band": ["U2"],
    "Bird": ["Umbrellabird"],
    "Body part (human)": ["Uterus"],
    "Book title": ["Uglies"],
    "Boys name": ["Umar"],
    "Car make / Model": ["Ultima"],
    "Country": ["Uruguay"],
    "Dog breed": ["Utonagan"],
    "Drink": ["Um Bongo"],
    "Eat (Food)": ["Udon noodles"],
    "Fictional character": ["Ultron"],
    "Film": ["Us"],
    "Fish": ["Uaru"],
    "Foreign city": ["Usera"],
    "Foreign language": ["Urdu"],
    "Fruit / Vegetable": ["/ Urad bean"],
    "Girls name": ["Ursula"],
    "Hobby": ["Ultimate Frisbee"],
    "Job title": ["Understudy"],
    "Musical instrument": ["Ukelele"],
    "Plant or flower": ["Ursinia"],
    "School Subject": ["UK History"],
    "Shop": ["USC"],
    "Song title": ["Unfaithful"],
    "Sport": ["Unicycling"],
    "Sports star": ["Usain Bolt"],
    "TV show": ["Ugly Betty"],
    "UK City / Town": ["/Urmston"],
    "Wear (Clothing item)": ["Uniform"],
    "Word ending in ED": ["Used"],
    "Word ending in ING": ["Using"],
    "3/4/5 letter word": ["Use / User / Using"],
  },

  "V": {
    "Actor / Actress": ["Val Kilmer/ Vanessa Hudgens"],
    "Alcoholic Drink": ["Vodka"],
    "Animal": ["Vampire bat"],
    "Artist (Female singer)": ["Vera Lynn"],
    "Artist (Male singer)": ["Vanilla ice"],
    "Band": ["The Verve"],
    "Bird": ["Vulture"],
    "Body part (human)": ["Vertebrae"],
    "Book title": ["Velocity"],
    "Boys name": ["Victor"],
    "Car make / Model": ["Vauxhall / Vectra"],
    "Colour": ["Violet"],
    "Country": ["Vietnam"],
    "Dog breed": ["Vizsla"],
    "Drink": ["Vodka"],
    "Eat (Food)": ["Vegetables"],
    "Electrical appliance": ["Vacuum cleaner"],
    "Fictional character": ["Venom"],
    "Film": ["Venom"],
    "Fish": ["Vimba"],
    "Foreign city": ["Valenica"],
    "Foreign language": ["Vietnamese"],
    "Fruit / Vegetable": ["/ Velvet bean"],
    "Girls name": ["Vera"],
    "Hobby": ["Video games"],
    "Job title": ["Vet"],
    "Musical instrument": ["Violin"],
    "Plant or flower": ["Viola"],
    "School Subject": ["Visual Arts"],
    "Shop": ["Vans"],
    "Song title": ["Valerie"],
    "Sport": ["Volleyball"],
    "Sports star": ["Venus Williams"],
    "TV show": ["Vera"],
    "Wear (Clothing item)": ["Vest"],
    "Word ending in ED": ["Viewed"],
    "Word ending in ING": ["Viewing"],
    "3/4/5 letter word": ["Vow / View / Vigil"],
  },

  "W": {
    "Actor / Actress": ["Will Smith / Winona Ryder"],
    "Alcoholic Drink": ["Wine"],
    "Animal": ["Whale"],
    "Artist (Female singer)": ["Whitney Houston"],
    "Artist (Male singer)": ["Will Young"],
    "Band": ["The Who"],
    "Bird": ["Wren"],
    "Body part (human)": ["Wrist"],
    "Book title": ["War and Peace"],
    "Boys name": ["Will"],
    "Car make / Model": ["Winnebago / Wrangler"],
    "Colour": ["White"],
    "Country": ["Wales"],
    "Dog breed": ["Whippet"],
    "Drink": ["Water"],
    "Eat (Food)": ["Waffles"],
    "Electrical appliance": ["Washer"],
    "Fictional character": ["Wonder Woman"],
    "Film": ["Wall-E"],
    "Fish": ["Waspfish"],
    "Football team (UK)": ["Wrexham"],
    "Foreign city": ["Warsaw"],
    "Foreign language": ["Wakhi"],
    "Fruit / Vegetable": ["Watermelon / Watercress"],
    "Girls name": ["Wendy"],
    "Hobby": ["Weaving"],
    "Job title": ["Waiter"],
    "Musical instrument": ["Wobble board"],
    "Plant or flower": ["Wisteria"],
    "School Subject": ["Woodwork"],
    "Shop": ["Wickes"],
    "Song title": ["Work"],
    "Sport": ["Wrestling"],
    "Sports star": ["Wayne Rooney"],
    "TV show": ["Wandavision"],
    "UK City / Town": ["Wrexham / Wakefield"],
    "Wear (Clothing item)": ["Watch"],
    "Word ending in ED": ["Watched"],
    "Word ending in ING": ["Winning"],
    "3/4/5 letter word": ["Win / Wine / Water"],
  },

  "X": {
    "Animal": ["X-ray tetra"],
    "Artist (Male singer)": ["Xzibit"],
    "Book title": ["X"],
    "Boys name": ["Xander"],
    "Car make / Model": ["X3"],
    "Dog breed": ["Xoloitzcuintle"],
    "Eat (Food)": ["Xanthan gum"],
    "Electrical appliance": ["Xbox"],
    "Fictional character": ["Xena warrior Princess"],
    "Film": ["X-men"],
    "Fish": ["X-ray tetra"],
    "Foreign city": ["Xi'an"],
    "Foreign language": ["Xiang"],
    "Girls name": ["Xena"],
    "Hobby": ["Xbox"],
    "Job title": ["X-ray operator"],
    "Musical instrument": ["Xylophone"],
    "Plant or flower": ["Xylosma"],
    "Song title": ["X Gon' Give It To Ya"],
    "Sport": ["Xare"],
    "Sports star": ["Xavi"],
    "TV show": ["Xfiles"],
    "3/4/5 letter word": ["Xray / Xenon"],
  },

  "Y": {
    "Actor / Actress": ["Yasmine Bleeth"],
    "Alcoholic Drink": ["Yaka"],
    "Animal": ["Yak"],
    "Artist (Female singer)": ["Yoko Ono"],
    "Artist (Male singer)": ["Yungblud"],
    "Band": ["Yazoo"],
    "Bird": ["Yellowhammer"],
    "Book title": ["You Suck"],
    "Boys name": ["Yan"],
    "Car make / Model": ["Yaris"],
    "Colour": ["Yellow"],
    "Country": ["Yemen"],
    "Dog breed": ["Yorkshire Terrier"],
    "Drink": ["Yop"],
    "Eat (Food)": ["Yogurt"],
    "Fictional character": ["Yoda"],
    "Film": ["Yentl"],
    "Fish": ["Yellow Tang"],
    "Football team (UK)": ["York city"],
    "Foreign city": ["Yangzhou"],
    "Foreign language": ["Yiddish"],
    "Fruit / Vegetable": ["/ Yam"],
    "Girls name": ["Yasmin"],
    "Hobby": ["Yodelling"],
    "Job title": ["Yachtsman"],
    "Musical instrument": ["Yangqin"],
    "Plant or flower": ["Yarrow"],
    "Shop": ["Yankee candle"],
    "Song title": ["Yesterday"],
    "Sport": ["Yachting"],
    "Sports star": ["Yaya Touré"],
    "TV show": ["You"],
    "UK City / Town": ["York / Yarmouth"],
    "Wear (Clothing item)": ["Yoga top"],
    "Word ending in ED": ["Yearned"],
    "Word ending in ING": ["Yearning"],
    "3/4/5 letter word": ["Yes / Year / Yearn"],
  },

  "Z": {
    "Actor / Actress": ["Zachary Levi / Zendaya"],
    "Alcoholic Drink": ["Zombie"],
    "Animal": ["Zebra"],
    "Artist (Female singer)": ["Zendaya"],
    "Artist (Male singer)": ["Zac Efron"],
    "Band": ["Zutons"],
    "Book title": ["Zorro"],
    "Boys name": ["Zack"],
    "Car make / Model": ["Zoe"],
    "Country": ["Zimbabwe"],
    "Drink": ["Zapata"],
    "Eat (Food)": ["Ziti"],
    "Fictional character": ["Zorro"],
    "Film": ["Zodiac"],
    "Fish": ["Zebrafish"],
    "Foreign city": ["Zurich"],
    "Foreign language": ["Zulu"],
    "Fruit / Vegetable": ["/ Zucchini"],
    "Girls name": ["Zoe"],
    "Hobby": ["Zorbing"],
    "Job title": ["Zoo keeper"],
    "Musical instrument": ["Zither"],
    "Plant or flower": ["Zenobia"],
    "Shop": ["Zara"],
    "Song title": ["Zombie"],
    "Sport": ["Zorbing"],
    "Sports star": ["Zinedine Zidane"],
    "TV show": ["Zoo"],
    "Wear (Clothing item)": ["Zoris"],
    "Word ending in ED": ["Zoned"],
    "Word ending in ING": ["Zing"],
    "3/4/5 letter word": ["Zen / Zone / Zilch"],
  },

};
